Issue 401: Adding Info Icon to Priority Title in Map Legend
CodeForPhilly/vacant-lots-proj pull request #451
Opened 2024-03-20 17:02 UTC by mskNeo

https://github.com/CodeForPhilly/vacant-lots-proj/issues/401

Added the Phosphor Info Icon to the map legend. Had to hardcode it in CSS styling to get the specific icon from Phosphor Icons.

2024-03-20 19:09 UTC, paulhchoi commented
@mskNeo your PR covers the scope of this ticket, but for a more general UI/UX question: @thansidwell should hovering/clicking this icon show a tooltip? Just having an un-interactable 'i' icon feels like it may lead to some confusion, so if a tooltip should be added, I suggest we hold this PR as a draft until the tooltip is ready to be added.

2024-03-21 16:11 UTC, thansidwell commented
@paulhchoi Yes, we had intended when a user hovers over the icon a tooltip would show up explaining how we determine priority. We still don't have that written yet.

2024-03-21 19:38 UTC, mskNeo commented
I can try implementing a tooltip, but do we have any specific UI mockups/vision for it? @thansidwell

2024-03-21 21:21 UTC, thansidwell commented
@mskNeo That would be great if you could. There are a few other places we are using it. We are using the NextUI component library. Here's their tooltip. It's very close to what I designed.  https://nextui.org/docs/components/tooltip

Here's the documentation of what it should look like. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1435%3A8475&mode=design&t=rwvoZG2F2y3A2hfM-1

@brandonfcohen1 @paulhchoi Do we have a tooltip already?

2024-03-22 02:40 UTC, brandonfcohen1 commented
> @mskNeo That would be great if you could. There are a few other places we are using it. We are using the NextUI component library. Here's their tooltip. It's very close to what I designed. https://nextui.org/docs/components/tooltip
> 
> Here's the documentation of what it should look like. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1435%3A8475&mode=design&t=rwvoZG2F2y3A2hfM-1
> 
> @brandonfcohen1 @paulhchoi Do we have a tooltip already?

yeah we've been using nextui tooltip

2024-03-22 03:53 UTC, bacitracin commented
Hey @mskNeo ! When you add the NextUI tooltip, could you please add 2 quick a11y things?

1. Make the info icon keyboard accessible. So you should be able to TAB to the info icon, focus on it, and the tooltip will appear. Most likely all you need is to add a `tabIndex="0"` to the icon.
2. Add an alt text to the icon.

Here is a previous PR where I added these things https://github.com/CodeForPhilly/vacant-lots-proj/pull/350

Let me know if you have any questions!

2024-03-22 20:43 UTC, mskNeo commented
@bacitracin it seems like the map legend is autogenerated so adding the NextJS tooltip won't work since the legend elements are not in the codebase but rather rendered by the library. I'll try making a custom legend. @thansidwell are there any features of the legend as it is now that are being used? like collapsing it or anything?

2024-03-22 20:46 UTC, brandonfcohen1 commented
> @bacitracin it seems like the map legend is autogenerated so adding the NextJS tooltip won't work since the legend elements are not in the codebase but rather rendered by the library. That's why I used a CSS approach to add the info icon. I'll try making a custom legend. @thansidwell are there any features of the legend as it is now that are being used? like collapsing it or anything?

+1 on writing a custom legend

2024-03-25 02:29 UTC, mskNeo commented on package.json
> -    "mapboxgl-legend": "^1.14.0",
removing the legend library since we have a custom component now

2024-03-25 02:31 UTC, mskNeo commented on src/app/mapLegend.css
> +}
these are all from the mapboxgl-legend library, just copied all the CSS styles

2024-03-25 02:31 UTC, mskNeo commented on src/components/MapLegend.tsx
> +  };
now we should be able to add event listeners for the map, expand functionality and maybe add interactivity

2024-03-25 03:11 UTC, mskNeo commented on src/app/mapLegend.css
Got all these styles from the mapboxgl-legend we used to use

2024-03-25 03:11 UTC, mskNeo commented on src/components/MapLegendControl/MapLegend.tsx
> +  };
now able to add event listeners to map for legend, enabling interactivity

2024-03-25 14:30 UTC, brandonfcohen1 requested changes
@mskNeo deployment is failing- looks like you need to merge in the latest `staging`

2024-03-25 15:34 UTC, mskNeo commented on src/components/PropertyMap.tsx
> +          </Tooltip>,
<img width="1043" alt="Screenshot 2024-03-24 at 6 11 11 PM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/43150970/0c43a3b7-b954-4065-896f-a11c727fef17">
This is what it looks like now, should I make the tooltip a smaller width?

2024-03-25 15:36 UTC, mskNeo commented
> @mskNeo deployment is failing- looks like you need to merge in the latest `staging`

@brandonfcohen1  I synced my forked repo with staging and merged but it's still failing it seems

2024-03-25 16:06 UTC, thansidwell commented
@mskNeo I noticed we have two different style tooltips. On the live site and your tooltip. Are you using a different tooltip than what's used on the 'Download' and 'View' buttons? And both don't match the prototype. 

<img width="1102" alt="CleanShot 2024-03-25 at 11 59 18@2x" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6b2d2f02-32df-4796-96dc-2a3fee0593a6">

We should just be using one toolip component and it should look like the prototype. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1435%3A8475&mode=design&t=in6whOv1xRCIDRgL-1 

Can you fix that on this ticket or should I just write a new one?

2024-03-25 17:45 UTC, mskNeo commented
> > > @mskNeo deployment is failing- looks like you need to merge in the latest `staging`
> > 
> > 
> > @brandonfcohen1 I synced my forked repo with staging and merged but it's still failing it seems
> 
> here is the error- are you sure you have the latest `staging`? you can run `npm run build` locally to test the build before deploying
> 
> ```
> 
> Failed to compile.
> ./src/components/PropertyMap.tsx:41:23
> Type error: Cannot find module './ZoomModal' or its corresponding type declarations.
>   39 | import MapboxGeocoder from "@mapbox/mapbox-gl-geocoder";
>   40 | import "@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css";
> > 41 | import ZoomModal from "./ZoomModal";
>      |                       ^
>   42 | import { Coordinates } from "../app/types";
>   43 | import { MapLegendControl } from "./MapLegendControl";
>   44 | import { createPortal } from "react-dom";
> Error: Command "npm run build" exited with 1
> ```

@brandonfcohen1 My forked repository for some reason wasn't syncing properly with the staging branch, thankfully my main branch did so I had to manually check out the missing files. Hopefully that works

2024-03-25 18:15 UTC, brandonfcohen1 commented
legend looks great. Will let @thansidwell approve the UI

Is it intended that clicking the `i` icon minimizes the legend?

2024-03-25 18:19 UTC, mskNeo commented
> legend looks great. Will let @thansidwell approve the UI
> 
> Is it intended that clicking the `i` icon minimizes the legend?

@brandonfcohen1 clicking the upper bar of the legend in general minimizes, not just the I. So clicking on the empty space to the right of it closes it too. This is the same behavior as the library legend that we had before.

2024-03-25 18:41 UTC, brandonfcohen1 commented
> > legend looks great. Will let @thansidwell approve the UI
> > Is it intended that clicking the `i` icon minimizes the legend?
> 
> @brandonfcohen1 clicking the upper bar of the legend in general minimizes, not just the I. So clicking on the empty space to the right of it closes it too. This is the same behavior as the library legend that we had before.

haha nice, had never clicked that before

2024-03-25 18:42 UTC, brandonfcohen1 approved these changes
approved by me, awaiting @thansidwell

2024-03-25 18:53 UTC, thansidwell commented
It looks good to me! 

I'll write another ticket to make further styling updates to the tooltip.

2024-03-25 18:54 UTC, merged