config and doc changes for a more robust backend setup
CodeForPhilly/vacant-lots-proj pull request #545
Opened 2024-04-19 03:51 UTC by zigouras

I got the frontend and backend working on my WSL Ubuntu setup on Windows.  I found some small areas for improvement in configuration and documentation as I worked through some setup issues with Brandon.

2024-04-19 12:34 UTC, brandonfcohen1 requested changes
this is awesome, thank you so much @zigouras 

question- did you have any trouble with the CORS setup on the bucket? should we add some documentation about that?

2024-04-19 16:41 UTC, Moylena commented
@zigouras  can you make the change requested? Then I think this will be all set

2024-04-19 16:49 UTC, brandonfcohen1 approved these changes

2024-04-19 16:50 UTC, merged

2024-04-20 00:27 UTC, zigouras commented
> this is awesome, thank you so much @zigouras
> 
> question- did you have any trouble with the CORS setup on the bucket? should we add some documentation about that?

It wasn't CORS after all, it was simply the permissions on my bucket in GCP.  I had to let the 'allUsers' principal have read access to the bucket.  This makes it publicly available on the web the same as the prod bucket.